import React, { useState, useMemo } from 'react';
import { 
  HelpCircle, 
  CheckCircle2, 
  XCircle, 
  ArrowRight, 
  RotateCcw, 
  Sparkles, 
  Trophy,
  BookOpen,
  Award,
  UploadCloud
} from 'lucide-react';
import { ExtractedResumeData } from './WelcomeSection';
import { ROLE_ROADMAP_TOPICS } from './PersonalizedLearningRoadmap';

interface QuizPageProps {
  targetRole: string;
  targetRoleId?: string | null;
  isAnalyzed: boolean;
  extractedData: ExtractedResumeData | null;
  onNavigate?: (tab: string) => void;
  showToast?: (msg: string) => void;
}

export interface QuizQuestion {
  id: string;
  topicName: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

// Question Bank mapped directly to Learning Roadmap topics
const TOPIC_QUESTION_BANK: Record<string, QuizQuestion[]> = {
  'Python': [
    {
      id: 'py-1',
      topicName: 'Python',
      question: 'Which Python data structure is immutable and uses parentheses for definition?',
      options: ['List', 'Dictionary', 'Tuple', 'Set'],
      correctIndex: 2,
      explanation: 'Tuples are immutable sequences in Python defined using parentheses `()`, unlike lists which use square brackets `[]`.'
    },
    {
      id: 'py-2',
      topicName: 'Python',
      question: 'What is the primary benefit of using a generator expression or `yield` keyword over a list comprehension in Python?',
      options: ['Faster execution on small lists', 'Memory efficiency by evaluating items lazily', 'Automatic multithreading', 'Type checking at runtime'],
      correctIndex: 1,
      explanation: 'Generators compute values on-the-fly using lazy evaluation, saving significant RAM when handling massive datasets.'
    }
  ],

  'Statistics': [
    {
      id: 'stat-1',
      topicName: 'Statistics',
      question: 'In hypothesis testing, what does a p-value less than alpha (e.g., p < 0.05) indicate?',
      options: [
        'The null hypothesis is definitely true',
        'Reject the null hypothesis as there is statistically significant evidence',
        'Accept the null hypothesis without risk',
        'The sample size was too small'
      ],
      correctIndex: 1,
      explanation: 'A p-value below the threshold (typically 0.05) provides sufficient statistical evidence to reject the null hypothesis.'
    },
    {
      id: 'stat-2',
      topicName: 'Statistics',
      question: 'Which measure of central tendency is least sensitive to extreme outliers in a skewed continuous distribution?',
      options: ['Arithmetic Mean', 'Median', 'Mode', 'Variance'],
      correctIndex: 1,
      explanation: 'The median represents the middle value of ordered data and remains unaffected by extreme outlier values.'
    }
  ],

  'SQL': [
    {
      id: 'sql-1',
      topicName: 'SQL',
      question: 'Which SQL clause is used to filter aggregated data generated by a `GROUP BY` statement?',
      options: ['WHERE', 'ORDER BY', 'HAVING', 'JOIN'],
      correctIndex: 2,
      explanation: 'The `HAVING` clause filters aggregated grouped records, whereas `WHERE` filters individual rows prior to grouping.'
    },
    {
      id: 'sql-2',
      topicName: 'SQL',
      question: 'What is the main difference between `ROW_NUMBER()` and `RANK()` window functions when encountering tie values?',
      options: [
        '`ROW_NUMBER()` assigns identical ranks to ties; `RANK()` assigns unique integers',
        '`ROW_NUMBER()` assigns distinct sequential integers regardless of ties; `RANK()` skips ranks after ties',
        '`ROW_NUMBER()` requires `GROUP BY`; `RANK()` does not',
        '`ROW_NUMBER()` works only on strings'
      ],
      correctIndex: 1,
      explanation: 'ROW_NUMBER() always assigns unique sequential numbers (1,2,3), whereas RANK() gives duplicate values the same rank and skips subsequent numbers.'
    }
  ],

  'Pandas & NumPy': [
    {
      id: 'pd-1',
      topicName: 'Pandas & NumPy',
      question: 'In Pandas, which accessor function is specifically designed for label-based indexing and slicing of DataFrames?',
      options: ['df.iloc[]', 'df.loc[]', 'df.slice()', 'df.query()'],
      correctIndex: 1,
      explanation: '`df.loc[]` uses row and column labels for indexing, while `df.iloc[]` relies strictly on integer positions.'
    },
    {
      id: 'pd-2',
      topicName: 'Pandas & NumPy',
      question: 'What operation does NumPy perform when applying array arithmetic across arrays of different but compatible shapes?',
      options: ['Vector concatenation', 'Broadcasting', 'Matrix transposition', 'Dimensional flattening'],
      correctIndex: 1,
      explanation: 'Broadcasting allows NumPy to execute element-wise operations on arrays of varying shapes without creating unnecessary data copies.'
    }
  ],

  'Data Visualization': [
    {
      id: 'vis-1',
      topicName: 'Data Visualization',
      question: 'Which chart type is best suited for inspecting pairwise correlations between multiple numeric variables?',
      options: ['Pie Chart', 'Bar Chart', 'Correlation Heatmap', 'Box Plot'],
      correctIndex: 2,
      explanation: 'A correlation heatmap renders color-coded coefficients representing relationships between numeric column pairs.'
    }
  ],

  'Machine Learning': [
    {
      id: 'ml-1',
      topicName: 'Machine Learning',
      question: 'What problem occurs when a machine learning model achieves near-perfect accuracy on training data but performs poorly on unseen test data?',
      options: ['Underfitting', 'Overfitting', 'High Bias', 'Zero Variance'],
      correctIndex: 1,
      explanation: 'Overfitting occurs when a model memorizes noise in training samples, compromising its capacity to generalize to new data.'
    },
    {
      id: 'ml-2',
      topicName: 'Machine Learning',
      question: 'Which unsupervised learning technique reduces high-dimensional feature spaces by finding orthogonal principal axes?',
      options: ['Logistic Regression', 'K-Means Clustering', 'Principal Component Analysis (PCA)', 'Decision Trees'],
      correctIndex: 2,
      explanation: 'PCA projects high-dimensional data onto lower-dimensional orthogonal vectors while preserving maximum variance.'
    }
  ],

  'Model Evaluation': [
    {
      id: 'me-1',
      topicName: 'Model Evaluation',
      question: 'When evaluating a medical diagnosis model where missing a sick patient (false negative) is catastrophic, which metric should be maximized?',
      options: ['Accuracy', 'Precision', 'Recall (Sensitivity)', 'Specificity'],
      correctIndex: 2,
      explanation: 'Recall measures the proportion of actual positive cases correctly identified, minimizing dangerous false negatives.'
    }
  ],

  'Deployment': [
    {
      id: 'dep-1',
      topicName: 'Deployment',
      question: 'What is the role of Docker containerization when deploying machine learning models to cloud production environments?',
      options: [
        'To increase GPU clock speeds automatically',
        'To package code, libraries, and dependencies into reproducible, isolated runtime images',
        'To clean missing data in production databases',
        'To automatically tune hyperparameters'
      ],
      correctIndex: 1,
      explanation: 'Docker isolates code, environment configs, and system dependencies, guaranteeing consistent execution across local and cloud environments.'
    }
  ],

  'Excel': [
    {
      id: 'xl-1',
      topicName: 'Excel',
      question: 'Why is `XLOOKUP` generally preferred over traditional `VLOOKUP` in modern Excel analytical workflows?',
      options: [
        'XLOOKUP requires lookup values to be sorted in ascending order',
        'XLOOKUP can look up values to the left of the lookup column and defaults to exact match',
        'XLOOKUP only works on numeric values',
        'XLOOKUP cannot be combined with Pivot Tables'
      ],
      correctIndex: 1,
      explanation: 'XLOOKUP supports leftward lookups, defaults to exact match without column index counts, and handles missing values cleanly.'
    }
  ],

  'Power BI/Tableau': [
    {
      id: 'pbi-1',
      topicName: 'Power BI/Tableau',
      question: 'In Power BI, what language is used to write custom calculated columns and dynamic aggregated measures?',
      options: ['M Query', 'DAX (Data Analysis Expressions)', 'SQL', 'Python'],
      correctIndex: 1,
      explanation: 'DAX is the analytical query expression language used in Power BI and Analysis Services for dynamic metrics.'
    }
  ],

  'Business Analysis': [
    {
      id: 'ba-1',
      topicName: 'Business Analysis',
      question: 'What metric measures the percentage of users who stop subscribing or using a product over a given timeframe?',
      options: ['Conversion Rate', 'Cohort Growth', 'Churn Rate', 'Customer Acquisition Cost (CAC)'],
      correctIndex: 2,
      explanation: 'Churn rate quantifies user loss over a specific period, serving as a key indicator of product retention.'
    }
  ],

  'Deep Learning': [
    {
      id: 'dl-1',
      topicName: 'Deep Learning',
      question: 'In neural network training, what algorithm calculates partial derivatives of the loss function with respect to weights using the chain rule?',
      options: ['Convolution', 'Backpropagation', 'Dropout', 'Softmax Activation'],
      correctIndex: 1,
      explanation: 'Backpropagation applies the chain rule backward through neural layers to calculate weight gradients for optimization.'
    }
  ],

  'NLP/Computer Vision': [
    {
      id: 'nlp-1',
      topicName: 'NLP/Computer Vision',
      question: 'What architectural innovation enables Transformer models to process all tokens in a sequence concurrently rather than sequentially?',
      options: ['Recurrent Feedback Loops', 'Self-Attention Mechanism', 'Max Pooling Layers', 'Edge Filters'],
      correctIndex: 1,
      explanation: 'Self-attention calculates pairwise relationships between all tokens simultaneously, unlocking parallel processing.'
    }
  ],

  'APIs': [
    {
      id: 'api-1',
      topicName: 'APIs',
      question: 'In FastAPI, which library is used for request data parsing, type validation, and automatic OpenAPI schema generation?',
      options: ['Flask', 'Pydantic', 'Requests', 'Celery'],
      correctIndex: 1,
      explanation: 'Pydantic enforces strict type safety and request body validation in FastAPI microservices.'
    }
  ],

  'AI Application Development': [
    {
      id: 'rag-1',
      topicName: 'AI Application Development',
      question: 'What does RAG stand for in modern AI LLM application architecture?',
      options: [
        'Random Analytics Generation',
        'Retrieval-Augmented Generation',
        'Recurrent Automated Grid',
        'Relative Association Graph'
      ],
      correctIndex: 1,
      explanation: 'Retrieval-Augmented Generation fetches relevant context from external databases to ground LLM responses in real facts.'
    }
  ],

  'Data Structures & Algorithms': [
    {
      id: 'dsa-1',
      topicName: 'Data Structures & Algorithms',
      question: 'What is the average time complexity of searching for a value in a balanced Hash Table?',
      options: ['O(1)', 'O(log N)', 'O(N)', 'O(N^2)'],
      correctIndex: 0,
      explanation: 'Hash tables offer O(1) constant average time lookup using direct key-to-bucket index mapping.'
    }
  ],

  'TypeScript/JavaScript': [
    {
      id: 'ts-1',
      topicName: 'TypeScript/JavaScript',
      question: 'What keyword in TypeScript allows creating reusable components or functions that work with arbitrary types while preserving type safety?',
      options: ['any', 'unknown', 'Generics (`<T>`)', 'interface'],
      correctIndex: 2,
      explanation: 'Generics (`<T>`) allow writing flexible, type-safe functions and abstractions without falling back to type-unsafe `any`.'
    }
  ],

  'Frontend Engineering': [
    {
      id: 'fe-1',
      topicName: 'Frontend Engineering',
      question: 'In React, why should you avoid mutating state objects directly (e.g. `state.items.push(newItem)`)?',
      options: [
        'React state is read-only in memory',
        'Direct mutation bypasses React shallow comparison, preventing component re-renders',
        'It causes automatic server restarts',
        'Push operations are not supported in JavaScript'
      ],
      correctIndex: 1,
      explanation: 'React detects state changes by comparing object references; mutating objects directly skips re-rendering.'
    }
  ],

  'Databases': [
    {
      id: 'db-1',
      topicName: 'Databases',
      question: 'What property of ACID compliant databases ensures that a transaction is completely committed or entirely rolled back if a failure occurs?',
      options: ['Atomicity', 'Consistency', 'Isolation', 'Durability'],
      correctIndex: 0,
      explanation: 'Atomicity guarantees that all operations within a transaction execute as a single "all-or-nothing" unit.'
    }
  ]
};

// Fallback questions if specific roadmap topics need additional questions to reach 10
const GENERAL_FALLBACK_QUESTIONS: QuizQuestion[] = [
  {
    id: 'gen-1',
    topicName: 'Version Control & Git',
    question: 'Which Git command creates a new isolated workspace branch and switches to it in a single step?',
    options: ['git branch <name>', 'git checkout -b <name>', 'git merge <name>', 'git commit -m <name>'],
    correctIndex: 1,
    explanation: '`git checkout -b <name>` (or `git switch -c <name>`) creates and immediately checks out a new feature branch.'
  },
  {
    id: 'gen-2',
    topicName: 'Software Architecture',
    question: 'What is the main benefit of adhering to the Single Responsibility Principle (SRP) in clean code architecture?',
    options: [
      'Increases code execution speed by 50%',
      'Ensures a class or module has only one reason to change, making code maintainable and testable',
      'Eliminates the need for unit tests',
      'Forces all functions to sit in one file'
    ],
    correctIndex: 1,
    explanation: 'SRP isolates concerns so modifications to one business rule do not inadvertently break unrelated features.'
  }
];

export const QuizPage: React.FC<QuizPageProps> = ({
  targetRole,
  targetRoleId,
  isAnalyzed,
  extractedData,
  onNavigate,
  showToast,
}) => {
  // 1. Identify Candidate Roadmap Topics
  const normRoleId = (targetRoleId || 'data-scientist').toLowerCase().replace(/^custom-/, '');
  const roadmapTopics = ROLE_ROADMAP_TOPICS[normRoleId] || ROLE_ROADMAP_TOPICS['data-scientist'];

  // 2. Dynamically Assemble 10 Multiple-Choice Questions strictly based on candidate's Roadmap Topics
  const quizQuestions: QuizQuestion[] = useMemo(() => {
    const questions: QuizQuestion[] = [];
    const usedIds = new Set<string>();

    // Pull questions from roadmap topics first
    for (const topicObj of roadmapTopics) {
      const bank = TOPIC_QUESTION_BANK[topicObj.topicName] || TOPIC_QUESTION_BANK['Python'] || [];
      for (const q of bank) {
        if (!usedIds.has(q.id) && questions.length < 10) {
          questions.push(q);
          usedIds.add(q.id);
        }
      }
    }

    // Fill remaining up to 10 from general pool if needed
    for (const topicKey in TOPIC_QUESTION_BANK) {
      if (questions.length >= 10) break;
      for (const q of TOPIC_QUESTION_BANK[topicKey]) {
        if (!usedIds.has(q.id) && questions.length < 10) {
          questions.push(q);
          usedIds.add(q.id);
        }
      }
    }

    for (const q of GENERAL_FALLBACK_QUESTIONS) {
      if (questions.length >= 10) break;
      if (!usedIds.has(q.id)) {
        questions.push(q);
        usedIds.add(q.id);
      }
    }

    return questions.slice(0, 10);
  }, [normRoleId, roadmapTopics]);

  // Quiz State
  const [currentQIdx, setCurrentQIdx] = useState(0);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, number>>({});
  const [isQuizSubmitted, setIsQuizSubmitted] = useState(false);

  if (!isAnalyzed || !extractedData) {
    return (
      <div className="rounded-3xl border border-slate-800/80 bg-slate-900/60 p-8 sm:p-12 text-center backdrop-blur-xl shadow-2xl space-y-6">
        <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-cyan-500/10 border border-cyan-500/30 text-cyan-400">
          <BookOpen className="h-8 w-8" />
        </div>

        <div className="space-y-2">
          <h2 className="text-xl sm:text-2xl font-extrabold text-white font-mono">
            Roadmap Topic Quiz
          </h2>
          <p className="text-sm font-semibold text-cyan-300 font-mono max-w-lg mx-auto">
            Upload and analyze your resume to generate your roadmap before taking the quiz.
          </p>
        </div>

        {onNavigate && (
          <div className="pt-2 flex justify-center">
            <button
              type="button"
              onClick={() => onNavigate('Dashboard')}
              className="flex items-center space-x-2 rounded-2xl bg-gradient-to-r from-cyan-500 to-indigo-600 px-6 py-3.5 text-xs font-bold text-white shadow-lg shadow-cyan-500/20 hover:scale-105 transition-all cursor-pointer"
            >
              <UploadCloud className="h-4 w-4" />
              <span>Go to Dashboard & Upload Resume</span>
            </button>
          </div>
        )}
      </div>
    );
  }

  const currentQuestion = quizQuestions[currentQIdx];
  const isSelected = selectedAnswers[currentQIdx] !== undefined;

  const handleSelectOption = (optIdx: number) => {
    if (isQuizSubmitted) return;
    setSelectedAnswers((prev) => ({ ...prev, [currentQIdx]: optIdx }));
  };

  const handleNext = () => {
    if (currentQIdx < quizQuestions.length - 1) {
      setCurrentQIdx((prev) => prev + 1);
    } else {
      setIsQuizSubmitted(true);
      if (showToast) showToast('Quiz completed! Review your score below.');
    }
  };

  // Calculate score
  const score = quizQuestions.reduce((acc, q, idx) => {
    return selectedAnswers[idx] === q.correctIndex ? acc + 1 : acc;
  }, 0);

  const scorePct = Math.round((score / quizQuestions.length) * 100);

  const handleRetake = () => {
    setCurrentQIdx(0);
    setSelectedAnswers({});
    setIsQuizSubmitted(false);
  };

  return (
    <div className="space-y-8 animate-fadeIn">
      
      {/* Header Banner */}
      <div className="relative overflow-hidden rounded-3xl border border-slate-800/80 bg-gradient-to-r from-slate-900/90 via-slate-900/70 to-purple-950/40 p-6 sm:p-8 backdrop-blur-xl shadow-2xl space-y-3">
        <div className="inline-flex items-center space-x-2 rounded-full border border-cyan-500/30 bg-cyan-500/10 px-3.5 py-1 text-xs font-medium text-cyan-300">
          <Sparkles className="h-3.5 w-3.5 text-cyan-400" />
          <span>Roadmap Technical Knowledge Check</span>
        </div>

        <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-white font-mono">
          Quiz: <span className="text-cyan-400">{targetRole}</span> Roadmap Topics
        </h1>
        <p className="text-xs sm:text-sm text-slate-400 max-w-2xl leading-relaxed">
          10 targeted questions derived strictly from the topics in your personalized <strong className="text-white">{targetRole}</strong> learning roadmap.
        </p>
      </div>

      {/* ========================================================= */}
      {/* QUIZ IN PROGRESS (ONE QUESTION AT A TIME) */}
      {/* ========================================================= */}
      {!isQuizSubmitted ? (
        <div className="rounded-3xl border border-slate-800 bg-slate-900/60 p-6 sm:p-8 backdrop-blur-xl shadow-2xl space-y-6">
          
          {/* Progress Bar & Header */}
          <div className="space-y-3 border-b border-slate-800 pb-4">
            <div className="flex items-center justify-between text-xs font-mono">
              <span className="font-bold text-cyan-400 uppercase tracking-wider">
                Question {currentQIdx + 1} of {quizQuestions.length}
              </span>
              <span className="rounded-full bg-cyan-500/10 border border-cyan-500/30 px-3 py-1 text-cyan-300 font-bold">
                Topic: {currentQuestion.topicName}
              </span>
            </div>

            {/* Stepper Bar */}
            <div className="h-2 w-full rounded-full bg-slate-950 overflow-hidden border border-slate-800">
              <div 
                className="h-full bg-gradient-to-r from-cyan-500 to-indigo-600 transition-all duration-300"
                style={{ width: `${((currentQIdx + 1) / quizQuestions.length) * 100}%` }}
              />
            </div>
          </div>

          {/* Question Text */}
          <div className="space-y-4">
            <h2 className="text-base sm:text-lg font-extrabold text-white font-mono leading-relaxed">
              {currentQuestion.question}
            </h2>

            {/* 4 Options */}
            <div className="grid grid-cols-1 gap-3">
              {currentQuestion.options.map((optionText, optIdx) => {
                const isOptionSelected = selectedAnswers[currentQIdx] === optIdx;

                return (
                  <button
                    key={optIdx}
                    type="button"
                    onClick={() => handleSelectOption(optIdx)}
                    className={`w-full flex items-center justify-between rounded-2xl border p-4 text-left text-xs sm:text-sm font-medium transition-all ${
                      isOptionSelected
                        ? 'border-cyan-400 bg-cyan-950/40 text-cyan-200 font-bold shadow-lg shadow-cyan-950/40'
                        : 'border-slate-800/90 bg-slate-950/60 text-slate-300 hover:border-slate-700 hover:bg-slate-900/80'
                    }`}
                  >
                    <div className="flex items-center space-x-3">
                      <span className={`flex h-6 w-6 items-center justify-center rounded-xl text-xs font-mono font-bold shrink-0 ${
                        isOptionSelected ? 'bg-cyan-500 text-slate-950' : 'bg-slate-800 text-slate-400'
                      }`}>
                        {String.fromCharCode(65 + optIdx)}
                      </span>
                      <span>{optionText}</span>
                    </div>

                    {isOptionSelected && (
                      <CheckCircle2 className="h-5 w-5 text-cyan-400 shrink-0" />
                    )}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Bottom Action Controls */}
          <div className="pt-4 border-t border-slate-800 flex items-center justify-between">
            <button
              type="button"
              disabled={currentQIdx === 0}
              onClick={() => setCurrentQIdx((prev) => Math.max(0, prev - 1))}
              className="text-xs font-semibold text-slate-400 hover:text-white disabled:opacity-30 transition-colors"
            >
              ← Previous Question
            </button>

            <button
              type="button"
              disabled={!isSelected}
              onClick={handleNext}
              className="flex items-center space-x-2 rounded-xl bg-gradient-to-r from-cyan-500 to-indigo-600 px-6 py-3 text-xs font-extrabold text-white shadow-lg hover:scale-105 disabled:opacity-40 transition-all cursor-pointer"
            >
              <span>{currentQIdx === quizQuestions.length - 1 ? 'Submit Quiz' : 'Next Question'}</span>
              <ArrowRight className="h-4 w-4" />
            </button>
          </div>

        </div>
      ) : (
        /* ========================================================= */
        /* QUIZ RESULTS & SCORE BREAKDOWN */
        /* ========================================================= */
        <div className="space-y-8 animate-fadeIn">
          
          {/* Score Hero Box */}
          <div className="rounded-3xl border border-slate-800 bg-slate-900/80 p-8 text-center backdrop-blur-xl shadow-2xl space-y-6">
            <div className="mx-auto flex h-20 w-20 items-center justify-center rounded-3xl bg-cyan-500/10 border border-cyan-500/30 text-cyan-400">
              <Trophy className="h-10 w-10" />
            </div>

            <div className="space-y-2">
              <span className="text-xs font-bold text-cyan-400 font-mono uppercase tracking-wider">
                Quiz Completed
              </span>
              <h2 className="text-3xl font-extrabold text-white font-mono">
                Your Score: <span className="text-cyan-400">{score} / 10</span> ({scorePct}%)
              </h2>
              <p className="text-xs text-slate-400 max-w-md mx-auto">
                {scorePct >= 80 
                  ? 'Excellent job! You demonstrated strong mastery across your target roadmap topics.' 
                  : scorePct >= 50 
                  ? 'Solid effort! Review the detailed explanations below to reinforce missing concepts.' 
                  : 'Keep learning! Use your roadmap topics to bridge the remaining knowledge gaps.'}
              </p>
            </div>

            <div className="pt-2 flex justify-center space-x-4">
              <button
                type="button"
                onClick={handleRetake}
                className="flex items-center space-x-2 rounded-xl bg-slate-800 hover:bg-slate-700 px-5 py-3 text-xs font-bold text-white transition-colors"
              >
                <RotateCcw className="h-4 w-4" />
                <span>Retake Quiz</span>
              </button>

              {onNavigate && (
                <button
                  type="button"
                  onClick={() => onNavigate('Learning Roadmap')}
                  className="flex items-center space-x-2 rounded-xl bg-gradient-to-r from-cyan-500 to-indigo-600 px-5 py-3 text-xs font-bold text-white shadow-lg hover:scale-105 transition-all"
                >
                  <BookOpen className="h-4 w-4" />
                  <span>Return to Learning Roadmap</span>
                </button>
              )}
            </div>
          </div>

          {/* Answers Breakdown & Explanations */}
          <div className="rounded-3xl border border-slate-800 bg-slate-900/60 p-6 sm:p-8 backdrop-blur-xl shadow-2xl space-y-6">
            <div className="flex items-center space-x-3 border-b border-slate-800 pb-4">
              <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-cyan-500/20 text-cyan-400 font-bold border border-cyan-500/30">
                <HelpCircle className="h-5 w-5" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-white font-mono">
                  Detailed Answer Review
                </h3>
                <p className="text-xs text-slate-400">
                  Review correct answers and technical explanations for each roadmap question
                </p>
              </div>
            </div>

            <div className="space-y-4">
              {quizQuestions.map((q, idx) => {
                const userChoice = selectedAnswers[idx];
                const isCorrect = userChoice === q.correctIndex;

                return (
                  <div 
                    key={q.id}
                    className={`rounded-2xl border p-5 space-y-3 ${
                      isCorrect 
                        ? 'border-emerald-500/30 bg-emerald-950/10' 
                        : 'border-rose-500/30 bg-rose-950/10'
                    }`}
                  >
                    <div className="flex items-center justify-between border-b border-slate-800/80 pb-2">
                      <span className="text-xs font-bold font-mono text-cyan-400">
                        Q{idx + 1}: {q.topicName}
                      </span>

                      <span className={`flex items-center space-x-1 text-xs font-extrabold px-2.5 py-0.5 rounded-full ${
                        isCorrect ? 'bg-emerald-500/20 text-emerald-300' : 'bg-rose-500/20 text-rose-300'
                      }`}>
                        {isCorrect ? <CheckCircle2 className="h-3.5 w-3.5 mr-1" /> : <XCircle className="h-3.5 w-3.5 mr-1" />}
                        <span>{isCorrect ? 'Correct' : 'Incorrect'}</span>
                      </span>
                    </div>

                    <h4 className="text-sm font-bold text-white font-mono">
                      {q.question}
                    </h4>

                    <div className="space-y-1.5 text-xs">
                      <div className="text-slate-300">
                        <strong className="text-slate-400">Your Answer:</strong>{' '}
                        <span className={isCorrect ? 'text-emerald-300 font-semibold' : 'text-rose-300 font-semibold'}>
                          {userChoice !== undefined ? q.options[userChoice] : 'Not Answered'}
                        </span>
                      </div>

                      {!isCorrect && (
                        <div className="text-slate-300">
                          <strong className="text-slate-400">Correct Answer:</strong>{' '}
                          <span className="text-emerald-300 font-semibold">
                            {q.options[q.correctIndex]}
                          </span>
                        </div>
                      )}
                    </div>

                    <div className="rounded-xl bg-slate-950/80 p-3 border border-slate-800 text-xs text-slate-300 leading-relaxed">
                      <strong className="text-cyan-400 font-mono">Explanation:</strong> {q.explanation}
                    </div>
                  </div>
                );
              })}
            </div>

          </div>

        </div>
      )}

    </div>
  );
};
